//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: CheckTask.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol RMSServiceLinkGetTaskCall: ClientCallUnary {}

fileprivate final class RMSServiceLinkGetTaskCallBase: ClientCallUnaryBase<CheckTaskDto, RMSTaskDto>, RMSServiceLinkGetTaskCall {
  override class var method: String { return "/RMSServiceLink/GetTask" }
}


/// Instantiate RMSServiceLinkServiceClient, then call methods of this protocol to make API calls.
internal protocol RMSServiceLinkService: ServiceClient {
  /// Synchronous. Unary.
  func getTask(_ request: CheckTaskDto) throws -> RMSTaskDto
  /// Asynchronous. Unary.
  func getTask(_ request: CheckTaskDto, completion: @escaping (RMSTaskDto?, CallResult) -> Void) throws -> RMSServiceLinkGetTaskCall

}

internal final class RMSServiceLinkServiceClient: ServiceClientBase, RMSServiceLinkService {
  /// Synchronous. Unary.
  internal func getTask(_ request: CheckTaskDto) throws -> RMSTaskDto {
    return try RMSServiceLinkGetTaskCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getTask(_ request: CheckTaskDto, completion: @escaping (RMSTaskDto?, CallResult) -> Void) throws -> RMSServiceLinkGetTaskCall {
    return try RMSServiceLinkGetTaskCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol RMSServiceLinkProvider: ServiceProvider {
  func getTask(request: CheckTaskDto, session: RMSServiceLinkGetTaskSession) throws -> RMSTaskDto
}

extension RMSServiceLinkProvider {
  internal var serviceName: String { return "RMSServiceLink" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/RMSServiceLink/GetTask":
      return try RMSServiceLinkGetTaskSessionBase(
        handler: handler,
        providerBlock: { try self.getTask(request: $0, session: $1 as! RMSServiceLinkGetTaskSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol RMSServiceLinkGetTaskSession: ServerSessionUnary {}

fileprivate final class RMSServiceLinkGetTaskSessionBase: ServerSessionUnaryBase<CheckTaskDto, RMSTaskDto>, RMSServiceLinkGetTaskSession {}

